<?php

namespace App\Core\ContentAudit\Support;

final class ContentAuditPdfTypography
{
    /**
     * @param  mixed  $value
     */
    public static function formatValue(?string $label, $value): string
    {
        if ($value === null || $value === '') {
            return self::emptyHtml($label);
        }

        if (is_bool($value)) {
            return e($value ? 'Active' : 'Inactive');
        }

        $text = (string) $value;

        if (self::shouldRenderAsUrdu($label, $text)) {
            return self::urduSpan($text);
        }

        return nl2br(e($text));
    }

    public static function urduSpan(?string $text): string
    {
        if (! filled($text)) {
            return self::emptyHtml(null);
        }

        $normalized = ContentAuditUrduTextNormalizer::normalize($text);

        return '<span class="pdf-urdu" lang="ur" dir="rtl">'.nl2br(e($normalized)).'</span>';
    }

    public static function englishSpan(?string $text): string
    {
        if (! filled($text)) {
            return self::emptyHtml(null);
        }

        return '<span class="pdf-en" lang="en" dir="ltr">'.nl2br(e($text)).'</span>';
    }

    public static function emptyPlaceholder(?string $label): string
    {
        if (self::isAutoGeneratedField($label)) {
            return 'Will be generated automatically';
        }

        return '—';
    }

    public static function emptyHtml(?string $label): string
    {
        return '<span class="pdf-empty">'.e(self::emptyPlaceholder($label)).'</span>';
    }

    public static function compactValue(?string $label, ?string $text, int $limit = 320): string
    {
        $compact = ContentAuditPdfLayout::compact($text, $limit);

        return self::formatValue($label, $compact);
    }

    public static function mixedEnglishUrdu(string $english, ?string $urdu, string $separator = ' — '): string
    {
        $html = '<span class="pdf-en" lang="en" dir="ltr">'.e($english).'</span>';

        if (filled($urdu)) {
            $html .= '<span class="pdf-mixed-sep" dir="ltr">'.e($separator).'</span>'
                .self::urduSpan($urdu);
        }

        return $html;
    }

    public static function shouldRenderAsUrdu(?string $label, ?string $text): bool
    {
        if (self::isUrduFieldLabel($label ?? '')) {
            return true;
        }

        return self::containsArabicScript($text);
    }

    public static function isUrduFieldLabel(string $label): bool
    {
        return (bool) preg_match('/\((?:Urdu|UR)\)|Urdu Name|Urdu\b/i', $label);
    }

    public static function containsArabicScript(?string $text): bool
    {
        if (! filled($text)) {
            return false;
        }

        return (bool) preg_match(
            '/[\x{0600}-\x{06FF}\x{0750}-\x{077F}\x{08A0}-\x{08FF}\x{FB50}-\x{FDFF}\x{FE70}-\x{FEFF}]/u',
            $text,
        );
    }

    protected static function isAutoGeneratedField(?string $label): bool
    {
        if (! filled($label)) {
            return false;
        }

        return (bool) preg_match(
            '/Description|Usage|Benefits|Warnings|Meta Description|SEO Title|Focus Keyword|Synonyms|Search Aliases|URL Slug/i',
            $label,
        );
    }
}
